name: 'recipe-management'
services:
  recipe-db:
    image: postgres:16-alpine
    container_name: recipe-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command: [ 'start-dev', '--import-realm', '--http-port=9191' ]
    container_name: keycloak
    hostname: keycloak
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=recipe_admin
      - KEYCLOAK_ADMIN_PASSWORD=recipe_admin_password
    ports:
      - "9191:9191"
    deploy:
      resources:
        limits:
          memory: 2gb